try{console.log("Hello Console.")}catch(e$$5){window.console={};for(var cMethods="assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,markTimeline,profile,profileEnd,time,timeEnd,trace,warn".split(","),i=0;i<cMethods.length;i++)console[cMethods[i]]=function(){}}
(function(b){function e(){var a=window.innerHeight,c=document.compatMode;if(c||!b.support.boxModel)a=c=="CSS1Compat"?document.documentElement.clientHeight:document.body.clientHeight;return a}var a=b("#access").outerHeight();b.fn.menuview=function(a){b.extend({optionOne:"defaultValue",optionTwo:{partOne:"defaultValue"}},a)};b(window).scroll(function(){var d=e(),c=document.documentElement.scrollTop?document.documentElement.scrollTop:document.body.scrollTop,g=[];c+=a;b.each(b.cache,function(){if(this.events&&
this.events.menuview){if(this.events.menuview){var a=this.events.menuview[0].data.additional_div;b(this.handle.elem).data("associated_div",a)}g.push(this.handle.elem)}});g.length&&b(g).each(function(){var g=b(this),e=g.offset().top,f=g.height(),m=g.data("menuview")||!1,k=g.data("associated_div").height();if(c<e||c+d>e+f+(d-k)){if(m){var l;c+a+d>e+f+(d-k)?l="bottom":c+a<e&&(l="top");g.data("menuview",!1);g.trigger("menuview",[!0,"out",l])}}else if((c>=e-k||c+d<=e+f)&&!m)l="top",c+d>e+f&&(l="bottom"),
g.data("menuview",!0),g.trigger("menuview",[!0,"in",l])})});b(function(){b(window).trigger("scroll")})})(jQuery);
(function(b){window.EaseMap=function(e){var a=this,d={zoom:4,centerLat:38.7902935,centerLng:-97.64023729999997,mapHeight:380,minZoom:3,fitMarkers:!1,contId:"gmapCont",dataCont:".distributor-wrap",dataBlock:".distributor",dataAttr:"dist-data",locationKey:"distributor_street_address",fallbackLocationKey:"distributor_mailing_address",zoomControlStyle:"DEFAULT",streetViewControl:!1,scrollwheel:!1,mapTypeId:"ROADMAP",blocksAreClickable:!1,directionsLink:!1,globalInitID:"EaseMapInit"},c;for(c in e)d[c]=
e[c]||d[c];for(c in d)a[c]=d[c];a.loadingGoogle=!1;a.setupConstants=function(){if(typeof google!=="undefined"&&typeof google.maps!=="undefined")return window[a.globalInitID]&&(window[a.globalInitID]=void 0),a.loadingGoogle=!1,a.infowindow=new google.maps.InfoWindow,a.directionsService=new google.maps.DirectionsService,a.directionsDisplay=new google.maps.DirectionsRenderer,a.directionsDisplay.setMap(null),a.geocoder=new google.maps.Geocoder,a.center=null,a.cont=null,a.map=null,a.form=null,a.startAddy=
"",a.endAddy="",a.currentRoute=null,a.confirmBttn=null,a.dblclickListener=null,a.data=[],a.markers=[],a.init();else if(!a.loadingGoogle){a.loadingGoogle=!0;window[a.globalInitID]=a.setupConstants;var b=document.createElement("script");b.type="text/javascript";b.src="http://maps.googleapis.com/maps/api/js?sensor=false&callback="+a.globalInitID;document.body.appendChild(b)}};a.init=function(){a.setupMarkerData();a.setupMap();a.setupMarkers()};a.setupMap=function(){a.cont=document.getElementById(a.contId);
b(a.cont).height()||b(a.cont).height(a.mapHeight);a.center=new google.maps.LatLng(a.centerLat,a.centerLng);a.map=new google.maps.Map(a.cont,{center:a.center,zoom:a.zoom,zoomControlOptions:{style:google.maps.ZoomControlStyle[a.zoomControlStyle]},streetViewControl:a.streetViewControl,scrollwheel:a.scrollwheel,mapTypeId:google.maps.MapTypeId[a.mapTypeId]})};a.setupMarkers=function(){if(a.data.length){var c=new google.maps.LatLngBounds;b.each(a.data,function(d){var e=this,f=e[a.locationKey]||e[a.fallbackLocationKey];
f&&a.geocoder.geocode({address:a.stripTags(f)},function(f,k){k===google.maps.GeocoderStatus.OK?(a.markers[d]=new google.maps.Marker({map:a.map,position:f[0].geometry.location,item:e}),google.maps.event.addListener(a.markers[d],"mousedown",a.handleMarkerClick),a.blocksAreClickable&&b(e.DOM).attr({markerIndex:d}).mousedown(a.handleBlockClick).find("a").click(a.preventBlockLinks),a.fitMarkers&&(c.extend(a.markers[d].position),a.map.fitBounds(c))):alert("Geocode was not successful for the following reason: "+
k)})})}};a.preventBlockLinks=function(a){a.preventDefault()};a.handleBlockClick=function(){var c=a.markers[b(this).attr("markerIndex")],d={latLng:c.position};a.map.getZoom()<a.minZoom&&a.map.setZoom(a.minZoom);return a.handleMarkerClick.apply(c,[d])};a.handleMarkerClick=function(){var c='<div class="mapInfoDom">'+b(this.item.DOM).html();if(a.directionsLink){var d="http://maps.google.com/maps?saddr=&daddr="+this.item[a.locationKey].replace(/ /g,"+").replace(/\n/g,",+");c+='<a class="directionsLink" href="'+
d+'" title="Get directions to this site" target="_blank">Get Driving Directions</a>'}c+="</div>";a.infowindow.setContent(c);a.infowindow.open(a.map,this)};a.setupMarkerData=function(){return b(a.dataCont).find(a.dataBlock).each(function(){var c=JSON.parse(b(this).attr(a.dataAttr));c.DOM=this;a.data.push(c)})};a.stripTags=function(a){return typeof a!=="string"?!1:a.replace(/<([^>]+)>/g,"").replace(/\n|\r/g," ")};a.setupConstants();return a}})(jQuery);
(function(b){b.fn.lazyload=function(e){var a={threshold:0,failurelimit:0,event:"scroll",effect:"show",container:window};e&&b.extend(a,e);var d=this;"scroll"==a.event&&b(a.container).bind("scroll",function(){var c=0;d.each(function(){if(!b.abovethetop(this,a)&&!b.leftofbegin(this,a))if(!b.belowthefold(this,a)&&!b.rightoffold(this,a))b(this).trigger("appear");else if(c++>a.failurelimit)return!1});var e=b.grep(d,function(a){return!a.loaded});d=b(e)});this.each(function(){var c=this;void 0==b(c).attr("original")&&
b(c).attr("original",b(c).attr("src"));"scroll"!=a.event||void 0==b(c).attr("src")||a.placeholder==b(c).attr("src")||b.abovethetop(c,a)||b.leftofbegin(c,a)||b.belowthefold(c,a)||b.rightoffold(c,a)?(a.placeholder?b(c).attr("src",a.placeholder):b(c).removeAttr("src"),c.loaded=!1):c.loaded=!0;b(c).one("appear",function(){this.loaded||b("<img />").bind("load",function(){b(c).hide().attr("src",b(c).attr("original"))[a.effect](a.effectspeed);c.loaded=!0}).attr("src",b(c).attr("original"))});"scroll"!=a.event&&
b(c).bind(a.event,function(){c.loaded||b(c).trigger("appear")})});b(a.container).trigger(a.event);return this};b.belowthefold=function(e,a){return(a.container===void 0||a.container===window?b(window).height()+b(window).scrollTop():b(a.container).offset().top+b(a.container).height())<=b(e).offset().top-a.threshold};b.rightoffold=function(e,a){return(a.container===void 0||a.container===window?b(window).width()+b(window).scrollLeft():b(a.container).offset().left+b(a.container).width())<=b(e).offset().left-
a.threshold};b.abovethetop=function(e,a){return(a.container===void 0||a.container===window?b(window).scrollTop():b(a.container).offset().top)>=b(e).offset().top+a.threshold+b(e).height()};b.leftofbegin=function(e,a){return(a.container===void 0||a.container===window?b(window).scrollLeft():b(a.container).offset().left)>=b(e).offset().left+a.threshold+b(e).width()};b.extend(b.expr[":"],{"below-the-fold":"$.belowthefold(a, {threshold : 0, container: window})","above-the-fold":"!$.belowthefold(a, {threshold : 0, container: window})",
"right-of-fold":"$.rightoffold(a, {threshold : 0, container: window})","left-of-fold":"!$.rightoffold(a, {threshold : 0, container: window})"})})(jQuery);
(function(b){window.SyndicatedSubwayTiles=function(e){var a=this,d={url:"http://subwaytiles.bennya.com",wrapId:"content",count:1,speed:15,loadFromBottom:5E3,navEl:"nav#jsui",scrollSpeed:1E3,smoothScroll:!1,placeholderImage:Ease.TemplateUrl+"/images/transparent.gif"},c;for(c in e)d[c]=e[c]||d[c];for(c in d)a[c]=d[c];a.nav=null;a.navUl=null;a.wrap=null;a.timeout=null;a.placeholder="";a.page=1;a.getting=!1;a.localUrl=window.location.protocol+"//"+window.location.host+window.location.pathname;a.init=
function(){a.placeholder=a.placeholderImage;a.nav=b(a.navEl);a.navUl=a.nav.find("#posts");a.nav.find("#menuToggle").click(function(){a.navUl.slideToggle(200)});a.wrap=b("#"+a.wrapId).length?b("#"+a.wrapId):b("<div />",{id:a.wrapId}).appendTo("body");a.getPosts();b(a.wrap).parent().scroll(function(){a.getting||b(this).scrollTop()>b(a.wrap).height()-a.loadFromBottom&&a.getPosts()})};a.getPosts=function(){a.getting=!0;var c="?json=get_recent_posts&";a.count>0?c+="count="+a.count+"&":b.noop();c+="page="+
a.page;b.getJSON(a.url+c,function(c){c.posts.length&&b.each(c.posts,a.printPost);a.page+=1})};a.printPost=function(c,d){var e=b("<span />",{id:d.id}).appendTo(a.wrap);b("<a />",{href:"#"+d.id}).html(d.title).appendTo(a.navUl).wrap("<li>").click(a.navClick);a.timeoutPrint(0,e,d)};a.navClick=function(c){if(a.smoothScroll){c.preventDefault();var d=b(this).attr("href"),d=d.substr(1,d.length),c=b(a.wrap).find("#"+d).position(),d=b(a.wrap).find("#"+d).children().first();d.length&&(c=d.position());b(a.wrap).parent().animate({scrollTop:c.top+
"px"},a.scrollSpeed);return!1}};a.timeoutPrint=function(c,d,e){if(c<e.attachments.length){var f=e.attachments[c];if(f.mime_type.indexOf("image")>-1)f=f.images.full,b("<img />",{src:f.url,height:f.height,width:f.width}).appendTo(d).lazyload({placeholder:a.placeholder,effect:"fadeIn",container:a.wrap.parent()});a.timeout=setTimeout(function(){a.timeoutPrint(c+1,d,e)},a.speed)}else clearTimeout(a.timeout),a.getting=!1};a.init();return a}})(jQuery);
(function(b){var e=function(a,b){this.init("tooltip",a,b)};e.prototype={constructor:e,init:function(a,d,c){this.type=a;this.$element=b(d);this.options=this.getOptions(c);this.enabled=!0;this.options.trigger!="manual"&&(a=this.options.trigger=="hover"?"mouseenter":"focus",d=this.options.trigger=="hover"?"mouseleave":"blur",this.$element.on(a,this.options.selector,b.proxy(this.enter,this)),this.$element.on(d,this.options.selector,b.proxy(this.leave,this)));this.options.selector?this._options=b.extend({},
this.options,{trigger:"manual",selector:""}):this.fixTitle()},getOptions:function(a){a=b.extend({},b.fn[this.type].defaults,a,this.$element.data());if(a.delay&&typeof a.delay=="number")a.delay={show:a.delay,hide:a.delay};return a},enter:function(a){var d=b(a.currentTarget)[this.type](this._options).data(this.type);!d.options.delay||!d.options.delay.show?d.show():(d.hoverState="in",setTimeout(function(){d.hoverState=="in"&&d.show()},d.options.delay.show))},leave:function(a){var d=b(a.currentTarget)[this.type](this._options).data(this.type);
!d.options.delay||!d.options.delay.hide?d.hide():(d.hoverState="out",setTimeout(function(){d.hoverState=="out"&&d.hide()},d.options.delay.hide))},show:function(){var a,b,c,e,j,h,f;if(this.hasContent()&&this.enabled){a=this.tip();this.setContent();this.options.animation&&a.addClass("fade");h=typeof this.options.placement=="function"?this.options.placement.call(this,a[0],this.$element[0]):this.options.placement;b=/in/.test(h);a.remove().css({top:0,left:0,display:"block"}).appendTo(b?this.$element:document.body);
c=this.getPosition(b);e=a[0].offsetWidth;j=a[0].offsetHeight;switch(b?h.split(" ")[1]:h){case "bottom":f={top:c.top+c.height,left:c.left+c.width/2-e/2};break;case "top":f={top:c.top-j,left:c.left+c.width/2-e/2};break;case "left":f={top:c.top+c.height/2-j/2,left:c.left-e};break;case "right":f={top:c.top+c.height/2-j/2,left:c.left+c.width}}a.css(f).addClass(h).addClass("in")}},setContent:function(){var a=this.tip();a.find(".tooltip-inner").html(this.getTitle());a.removeClass("fade in top bottom left right")},
hide:function(){function a(){var a=setTimeout(function(){d.off(b.support.transition.end).remove()},500);d.one(b.support.transition.end,function(){clearTimeout(a);d.remove()})}var d=this.tip();d.removeClass("in");b.support.transition&&this.$tip.hasClass("fade")?a():d.remove()},fixTitle:function(){var a=this.$element;if(a.attr("title")||typeof a.attr("data-original-title")!="string")a.attr("data-original-title",a.attr("title")||"").removeAttr("title")},hasContent:function(){return this.getTitle()},
getPosition:function(a){return b.extend({},a?{top:0,left:0}:this.$element.offset(),{width:this.$element[0].offsetWidth,height:this.$element[0].offsetHeight})},getTitle:function(){var a;a=this.$element;var b=this.options;a=a.attr("data-original-title")||(typeof b.title=="function"?b.title.call(a[0]):b.title);return a=(a||"").toString().replace(/(^\s*|\s*$)/,"")},tip:function(){return this.$tip=this.$tip||b(this.options.template)},validate:function(){if(!this.$element[0].parentNode)this.hide(),this.options=
this.$element=null},enable:function(){this.enabled=!0},disable:function(){this.enabled=!1},toggleEnabled:function(){this.enabled=!this.enabled},toggle:function(){this[this.tip().hasClass("in")?"hide":"show"]()}};b.fn.tooltip=function(a){return this.each(function(){var d=b(this),c=d.data("tooltip"),g=typeof a=="object"&&a;c||d.data("tooltip",c=new e(this,g));if(typeof a=="string")c[a]()})};b.fn.tooltip.Constructor=e;b.fn.tooltip.defaults={animation:!0,delay:0,selector:!1,placement:"top",trigger:"hover",
title:"",template:'<div class="tooltip"><div class="tooltip-arrow"></div><div class="tooltip-inner"></div></div>'}})(window.jQuery);(function(b){function e(){var c=[{key:"#work",el:a("portfolio")},{key:"#about",el:a("home")},{key:"#places",el:b(".page-title strong")},{key:"#contact",el:b("a.contact")}];b.each(c,function(){if(b(this.key).length&&this.el.length){var a=this,c=function(d){d.preventDefault();var e=b(a.key).offset();b(window).scrollTop();$that=this;$args=arguments;b("html, body").stop(!1).animate({scrollTop:e.top-j+"px"},4*g,function(){var d=b(a.key).offset(),e=b(window).scrollTop();d.top-j-e>b(window).height()&&c.apply($that,
$args)});b("#header").find(".active").removeClass("active");b("#header").find(this).length&&a.el.parent().addClass("active")};a.el.click(c)}});c=null}function a(a){if(!a)return!1;var c=b("#header").find("a"),d=!1;b.each(c,function(){if(b(this).text().toLowerCase()==a)return d=b(this),!1});c=null;return d}function d(){var a=b("#subwayTilesLink");if(a)if(Ease.ie)a.attr({href:"http://subwaytiles.bennya.com",target:"_blank"});else{var c=b("#subwayTilesWrap");a.click(function(a){a.preventDefault();h||
(h=new SyndicatedSubwayTiles({wrapId:"subwayTiles",smoothScroll:!0}));c.show(250)});b("#closeSubwayTiles").click(function(){c.hide(250)})}a=null}function c(){if(b("#work").length){var a=function(a,c,d){b(window).scrollTop();c=d?0:c.outerHeight()-a.outerHeight();d=a.data("store_margin");a.css({position:"relative",top:c,left:0,marginLeft:d.left,marginTop:d.top})};b("#work").find(".pics").each(function(){var c=b(this),d=b(this).parent().children(".entry-box");c.find("img").each(function(){b(this).lazyload({placeholder:Ease.TemplateUrl+
"/images/transparent.gif",effect:"fadeIn"})});c.bind("menuview",{additional_div:d},function(b,e,g,h){e&&(g==="in"?(b=parseInt(d.css("margin-left").replace("px",""),10)||0,e=parseInt(d.css("margin-top").replace("px",""),10)||0,d.data("store_margin",{left:b,top:e}),d.css({position:"fixed",top:j,left:d.offset().left,marginLeft:0,marginTop:0}),margin_right=null):h==="bottom"?a(d,c,!1):a(d,c,!0))})})}}var g=350,j=null,h=!1;b(document).ready(function(){b("html.ie").length?Ease.ie=!0:Ease.ie=!1;b("html.lte8").length?
Ease.lte8=!0:Ease.lte8=!1;typeof WebKitPoint!=="undefined"?Ease.webkit=!0:Ease.webkit=!1;j=b("#access").outerHeight();c();b("#places").length&&new EaseMap({zoom:2,streetViewControl:!0,fitMarkers:!0,centerLat:36.153982,centerLng:-95.992775,dataCont:"#locationList",contId:"gMap",dataBlock:".locationItem",dataAttr:"ease-data",locationKey:"ba_place_address",directionsLink:!1,blocksAreClickable:!0});if(b("#resumeHref").length){var f=b("#resumeHref").text();b("#header").find("a");var g=a("resume");g&&g.attr({href:f,
target:"_blank"})}e();d();b(".page-title strong").tooltip({placement:"right"})})})(jQuery);
