try{console.log("Hello Console.")}catch(e$$5){window.console={};for(var cMethods="assert,count,debug,dir,dirxml,error,exception,group,groupCollapsed,groupEnd,info,log,markTimeline,profile,profileEnd,time,timeEnd,trace,warn".split(","),i=0;i<cMethods.length;i++)console[cMethods[i]]=function(){}}
(function(b){window.EaseYouTubePlayer=function(d){var a=this,f={user:"benjrallen",playlist:!1,maxResults:8,page:1,playerId:"easeYtPlayer",playerContId:"easeVideoPlayer",thumbsContId:"easeVideoBlocks",loadingMaskId:"easeLoadingMask",thumbBlockClass:"easeThumbBlock",imgContClass:"easeImg",imgLinkClass:"easeImgLink",imgClass:"easeVideoThumb",titleEl:"div",titleClass:"easeThumbTitle",descClass:"easeDesc",playClass:"easePlay",playText:"Play",playerCloseId:"easeClose",playerIsPopup:!1,playerCloseText:"x",
playerMaxHeight:853,playerPercent:0.8,playerRatioW:16,playerRatioH:9,paginateContId:"easePagin",navClass:"easeNav",navPrevText:"<< Prev",navNextText:"Next >>",flashPlayerSrc:"https://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js"},c;for(c in d)f[c]=d[c]||f[c];for(c in f)a[c]=f[c];a.CONSTANT="constant";a.API_URL="https://gdata.youtube.com/feeds/api/videos";a.API_USER_UPLOADS="https://gdata.youtube.com/feeds/api/users/"+a.user+"/uploads";a.API_USER_PLAYLISTS="https://gdata.youtube.com/feeds/api/users/"+
a.user+"/playlists";a.API_PLAYLIST_FEED="https://gdata.youtube.com/feeds/api/playlists/";a.ALT="jsonc";a.START_INDEX=null;a.TOTAL_ITEMS=null;a.LOADING=!0;a.loadTimeout=null;a.swfTimeout=null;a.FIRST_LOAD=!0;a.CURRENT_VIDEO=null;a.player=null;a.showPlayer=!1;a.IS_LTE7=b(".lte7").length;a.IS_LTE8=b(".lte8").length;a.IS_FLASH=!1;a.API_READY=!1;a.PLAYER_READY=!1;a.init=function(){a.IS_LTE7?a.loadSWFObject():a.loadIFrameAPI();a.playerCont=b("#"+a.playerContId);a.thumbsCont=b("#"+a.thumbsContId);if(!a.playerCont.length||
!a.thumbsCont.length)return alert("script won't run because video script has no place to put the player or the videos! please provide ids.");a.thumbsCont.addClass("easeVideos");a.updateStartIndex();a.loadingMask=b("#"+a.loadingMaskId);if(!a.loadingMask.length)a.loadingMask=b("<div />",{id:a.loadingMaskId}).prependTo(a.thumbsCont);a.loadingMask.show();if(a.playerIsPopup){a.playerClose=b("#"+a.playerCloseId);if(!a.playerClose.length)a.playerClose=b("<a />",{id:a.playerCloseId,text:a.playerCloseText,
title:"Close video"}).insertBefore(a.playerCont);b("body").click(a.onPlayerClose);b(window).resize(a.positionPlayer);b(document).scroll(a.positionPlayer)}return a.getVideos()};a.onYouTubePlayerAPIReady=function(){a.API_READY=!0;return a.loadPlayer()};a.loadIFrameAPI=function(){window.onYouTubePlayerAPIReady=a.onYouTubePlayerAPIReady;var b=document.createElement("script");b.src="http://www.youtube.com/player_api";var g=document.getElementsByTagName("script")[0];g.parentNode.insertBefore(b,g)};a.checkForSWFObject=
function(){return typeof swfobject==="undefined"?a.swfTimeout=setTimeout(a.checkForSWFObject,10):a.onYouTubePlayerAPIReady()};a.loadSWFObject=function(){a.IS_FLASH=!0;var b=document.createElement("script");b.src=a.flashPlayerSrc;b.async=!0;var g=document.getElementsByTagName("script")[0];g.parentNode.insertBefore(b,g);return a.checkForSWFObject()};a.getUserPlaylists=function(){if(a.user)return b.getJSON(a.API_USER_PLAYLISTS+"?callback=?",{alt:a.ALT,v:2},function(b){console.log("user: "+a.user+", playlists: ",
b)})};a.getVideos=function(){return b.getJSON((a.playlist?a.API_PLAYLIST_FEED+a.playlist:a.API_USER_UPLOADS)+"?callback=?",{alt:a.ALT,"max-results":a.maxResults,"start-index":a.START_INDEX,v:2},a.printVideoBlocks)};a.printVideoBlocks=function(e,g){a.LOADING=!1;if(g==="success"&&e.data)if(e.data.items){a.TOTAL_ITEMS=e.data.totalItems;b(".easeCont, #"+a.paginateContId).remove();for(var c=b("<div />",{}).addClass("easeCont").appendTo(a.thumbsCont),d=0,l=e.data.items.length;d<l;d++)a.makeVideoBlock(a.playlist?
e.data.items[d].video:e.data.items[d]).appendTo(c);e.data.totalItems>a.maxResults&&a.makePagination().insertAfter(a.thumbsCont);a.loadingMask.hide();if(a.FIRST_LOAD)a.FIRST_LOAD=!1,a.CURRENT_VIDEO=a.playlist?e.data.items[0].video:e.data.items[0]}else{if(!a.FIRST_LOAD)return a.page=1,a.updateStartIndex(),a.LOADING=!0,a.getVideos()}else e.error&&e.error.message&&a.thumbsCont.text(e.error.message)};a.onYouTubePlayerReady=function(b){a.onPlayerReady();return a.player=document.getElementById(b)};a.loadPlayer=
function(){if(!a.API_READY||!a.CURRENT_VIDEO)return a.loadTimeout=setTimeout(a.loadPlayer,10);var e=a.makePlayerDimensions();a.IS_FLASH?(window.onYouTubePlayerReady=a.onYouTubePlayerReady,swfobject.embedSWF("http://www.youtube.com/v/"+a.CURRENT_VIDEO.id+"?enablejsapi=1&playerapiid="+a.playerContId+"&version=3",a.playerContId,e.playerWidth,e.playerHeight,"8",null,null,{allowScriptAccess:"always"},{id:a.playerContId})):a.player=new YT.Player(a.playerContId,{height:e.playerHeight,width:e.playerWidth,
videoId:a.CURRENT_VIDEO.id,events:{onReady:a.onPlayerReady}});return a.playerCont=b("#"+a.playerContId)};a.onPlayerReady=function(){a.PLAYER_READY=!0};a.makePlayerDimensions=function(){var e=b(window).width(),g=b(window).height(),c=0,d=0;if(a.playerIsPopup){if(d=Math.floor(e*a.playerPercent),c=e<g?d:Math.floor(g*a.playerPercent*a.playerRatioW/a.playerRatioH),c>d&&(c=d),c>a.playerMaxHeight)c=a.playerMaxHeight}else c=b("#"+a.playerContId).width();d=Math.floor(a.playerRatioH/a.playerRatioW*c);return{baseWidth:e,
baseHeight:g,playerWidth:c,playerHeight:d}};a.positionPlayer=function(){if(a.player&&a.showPlayer&&a.PLAYER_READY){var b=a.makePlayerDimensions(),c=b.playerWidth,d=b.playerHeight,f=Math.floor((b.baseWidth-c)/2),b=Math.floor(b.baseHeight*0.1);!a.IS_FLASH?a.player.setSize(c,d):a.playerCont.width(c).height(d);a.playerCont.css({left:f,top:b});a.playerClose.css({left:f+c,top:b})}};a.loadVideo=function(){if(a.player&&a.PLAYER_READY)a.showPlayer=!0,a.player.loadVideoById(a.CURRENT_VIDEO.id,0,"large"),a.playerIsPopup&&
a.positionPlayer(),a.player.playVideo()};a.closePlayer=function(){if(a.player&&a.showPlayer)a.showPlayer=!1,a.player.stopVideo(),a.playerCont.css({left:-1E4}),a.playerClose.css({left:-1E4})};a.makePagination=function(){var e=b("<div />",{id:a.paginateContId});b("<div />").addClass("clearfix").appendTo(e);b("<a />",{text:a.navPrevText}).addClass(a.navClass+" prev").click(a.onPaginClick).appendTo(e);b("<a />",{text:a.navNextText}).addClass(a.navClass+" next").click(a.onPaginClick).appendTo(e);b("<span />",
{text:"Page "+a.page+" of "+Math.ceil(a.TOTAL_ITEMS/a.maxResults)}).appendTo(e);b("<div />").addClass("clearfix").appendTo(e);return e};a.makeVideoBlock=function(e){if(!e)return!1;var c=b("<div />",{}).addClass(a.thumbBlockClass).data({itemData:e}).click(a.onBlockPlay);e.thumbnail.sqDefault&&b("<div />",{html:'<a class="'+a.imgLinkClass+'" title="'+(e.title||"")+": "+(e.description||"")+'"><img src="'+e.thumbnail.sqDefault+'" class="'+a.imgClass+'" /></a>'}).addClass(a.imgContClass).appendTo(c);e.title&&
b("<"+a.titleEl+" />",{html:e.title}).addClass(a.titleClass).appendTo(c);e.description&&b("<div />",{html:e.description}).addClass(a.descClass).appendTo(c);b("<a />",{text:a.playText}).addClass(a.playClass).appendTo(c);return c};a.onPaginClick=function(){if(!a.LOADING)return b(this).hasClass("next")?a.page===Math.ceil(a.TOTAL_ITEMS/a.maxResults)?a.page=1:a.page++:a.page===1?a.page=Math.ceil(a.TOTAL_ITEMS/a.maxResults):a.page--,a.updateStartIndex(),a.loadingMask.show(),a.LOADING=!0,a.getVideos()};
a.onPlayerClose=function(b){b.target!==a.player&&a.closePlayer()};a.onBlockPlay=function(e){e.stopPropagation();a.CURRENT_VIDEO=b(this).data("itemData");return a.loadVideo()};a.updateStartIndex=function(){return a.START_INDEX=(a.page-1)*a.maxResults+1};a.init()}})(jQuery);
(function(b){window.EaseMap=function(d){var a=this,f={zoom:4,centerLat:38.7902935,centerLng:-97.64023729999997,mapHeight:380,minZoom:3,fitMarkers:!1,contId:"gmapCont",dataCont:".distributor-wrap",dataBlock:".distributor",dataAttr:"dist-data",locationKey:"distributor_street_address",fallbackLocationKey:"distributor_mailing_address",zoomControlStyle:"DEFAULT",streetViewControl:!1,scrollwheel:!1,mapTypeId:"ROADMAP",blocksAreClickable:!1,directionsLink:!1,globalInitID:"EaseMapInit"},c;for(c in d)f[c]=
d[c]||f[c];for(c in f)a[c]=f[c];a.loadingGoogle=!1;a.setupConstants=function(){if(typeof google!=="undefined")return window[a.globalInitID]&&(window[a.globalInitID]=void 0),a.loadingGoogle=!1,a.infowindow=new google.maps.InfoWindow,a.directionsService=new google.maps.DirectionsService,a.directionsDisplay=new google.maps.DirectionsRenderer,a.directionsDisplay.setMap(null),a.geocoder=new google.maps.Geocoder,a.center=null,a.cont=null,a.map=null,a.form=null,a.startAddy="",a.endAddy="",a.currentRoute=
null,a.confirmBttn=null,a.dblclickListener=null,a.data=[],a.markers=[],a.init();else if(!a.loadingGoogle){a.loadingGoogle=!0;window[a.globalInitID]=a.setupConstants;var b=document.createElement("script");b.type="text/javascript";b.src="http://maps.googleapis.com/maps/api/js?sensor=false&callback="+a.globalInitID;document.body.appendChild(b)}};a.init=function(){a.setupMarkerData();a.setupMap();a.setupMarkers()};a.setupMap=function(){a.cont=document.getElementById(a.contId);b(a.cont).height()||b(a.cont).height(a.mapHeight);
a.center=new google.maps.LatLng(a.centerLat,a.centerLng);a.map=new google.maps.Map(a.cont,{center:a.center,zoom:a.zoom,zoomControlOptions:{style:google.maps.ZoomControlStyle[a.zoomControlStyle]},streetViewControl:a.streetViewControl,scrollwheel:a.scrollwheel,mapTypeId:google.maps.MapTypeId[a.mapTypeId]})};a.setupMarkers=function(){if(a.data.length){var e=new google.maps.LatLngBounds;b.each(a.data,function(c){var d=this,f=d[a.locationKey]||d[a.fallbackLocationKey];f&&a.geocoder.geocode({address:a.stripTags(f)},
function(f,j){j===google.maps.GeocoderStatus.OK?(a.markers[c]=new google.maps.Marker({map:a.map,position:f[0].geometry.location,item:d}),google.maps.event.addListener(a.markers[c],"mousedown",a.handleMarkerClick),a.blocksAreClickable&&b(d.DOM).attr({markerIndex:c}).mousedown(a.handleBlockClick).find("a").click(a.preventBlockLinks),a.fitMarkers&&(e.extend(a.markers[c].position),a.map.fitBounds(e))):alert("Geocode was not successful for the following reason: "+j)})})}};a.preventBlockLinks=function(a){a.preventDefault()};
a.handleBlockClick=function(){var c=a.markers[b(this).attr("markerIndex")],d={latLng:c.position};a.map.getZoom()<a.minZoom&&a.map.setZoom(a.minZoom);return a.handleMarkerClick.apply(c,[d])};a.handleMarkerClick=function(){var c='<div class="mapInfoDom">'+b(this.item.DOM).html();if(a.directionsLink){var d="http://maps.google.com/maps?saddr=&daddr="+this.item[a.locationKey].replace(/ /g,"+").replace(/\n/g,",+");c+='<a class="directionsLink" href="'+d+'" title="Get directions to this site" target="_blank">Get Driving Directions</a>'}c+=
"</div>";a.infowindow.setContent(c);a.infowindow.open(a.map,this)};a.setupMarkerData=function(){return b(a.dataCont).find(a.dataBlock).each(function(){var c=JSON.parse(b(this).attr(a.dataAttr));c.DOM=this;a.data.push(c)})};a.stripTags=function(a){return typeof a!=="string"?!1:a.replace(/<([^>]+)>/g,"").replace(/\n|\r/g," ")};a.setupConstants();return a}})(jQuery);
(function(b){b.fn.lazyload=function(d){var a={threshold:0,failurelimit:0,event:"scroll",effect:"show",container:window};d&&b.extend(a,d);var f=this;"scroll"==a.event&&b(a.container).bind("scroll",function(){var c=0;f.each(function(){if(!b.abovethetop(this,a)&&!b.leftofbegin(this,a))if(!b.belowthefold(this,a)&&!b.rightoffold(this,a))b(this).trigger("appear");else if(c++>a.failurelimit)return!1});var e=b.grep(f,function(a){return!a.loaded});f=b(e)});this.each(function(){var c=this;void 0==b(c).attr("original")&&
b(c).attr("original",b(c).attr("src"));"scroll"!=a.event||void 0==b(c).attr("src")||a.placeholder==b(c).attr("src")||b.abovethetop(c,a)||b.leftofbegin(c,a)||b.belowthefold(c,a)||b.rightoffold(c,a)?(a.placeholder?b(c).attr("src",a.placeholder):b(c).removeAttr("src"),c.loaded=!1):c.loaded=!0;b(c).one("appear",function(){this.loaded||b("<img />").bind("load",function(){b(c).hide().attr("src",b(c).attr("original"))[a.effect](a.effectspeed);c.loaded=!0}).attr("src",b(c).attr("original"))});"scroll"!=a.event&&
b(c).bind(a.event,function(){c.loaded||b(c).trigger("appear")})});b(a.container).trigger(a.event);return this};b.belowthefold=function(d,a){return(a.container===void 0||a.container===window?b(window).height()+b(window).scrollTop():b(a.container).offset().top+b(a.container).height())<=b(d).offset().top-a.threshold};b.rightoffold=function(d,a){return(a.container===void 0||a.container===window?b(window).width()+b(window).scrollLeft():b(a.container).offset().left+b(a.container).width())<=b(d).offset().left-
a.threshold};b.abovethetop=function(d,a){return(a.container===void 0||a.container===window?b(window).scrollTop():b(a.container).offset().top)>=b(d).offset().top+a.threshold+b(d).height()};b.leftofbegin=function(d,a){return(a.container===void 0||a.container===window?b(window).scrollLeft():b(a.container).offset().left)>=b(d).offset().left+a.threshold+b(d).width()};b.extend(b.expr[":"],{"below-the-fold":"$.belowthefold(a, {threshold : 0, container: window})","above-the-fold":"!$.belowthefold(a, {threshold : 0, container: window})",
"right-of-fold":"$.rightoffold(a, {threshold : 0, container: window})","left-of-fold":"!$.rightoffold(a, {threshold : 0, container: window})"})})(jQuery);
(function(b){window.SyndicatedSubwayTiles=function(d){var a=this,f={url:"http://subwaytiles.bennya.com",wrapId:"content",count:1,speed:15,loadFromBottom:5E3,navEl:"nav#jsui",scrollSpeed:1E3,smoothScroll:!1,placeholderImage:Ease.TemplateUrl+"/images/transparent.gif"},c;for(c in d)f[c]=d[c]||f[c];for(c in f)a[c]=f[c];a.placeholder="";a.page=1;a.getting=!1;a.localUrl=window.location.protocol+"//"+window.location.host+window.location.pathname;a.init=function(){a.placeholder=a.placeholderImage;a.nav=b(a.navEl);
a.navUl=a.nav.find("#posts");a.nav.find("#menuToggle").click(function(){a.navUl.slideToggle(200)});a.wrap=b("#"+a.wrapId).length?b("#"+a.wrapId):b("<div />",{id:a.wrapId}).appendTo("body");a.getPosts();b(a.wrap).parent().scroll(function(){a.getting||b(this).scrollTop()>b(a.wrap).height()-a.loadFromBottom&&a.getPosts()})};a.getPosts=function(){a.getting=!0;var c="?json=get_recent_posts&";a.count>0?c+="count="+a.count+"&":b.noop();c+="page="+a.page;b.getJSON(a.url+c,function(c){c.posts.length&&b.each(c.posts,
a.printPost);a.page+=1})};a.printPost=function(c,d){var f=b("<span />",{id:d.id}).appendTo(a.wrap);b("<a />",{href:"#"+d.id}).html(d.title).appendTo(a.navUl).wrap("<li>").click(a.navClick);a.timeoutPrint(0,f,d)};a.navClick=function(c){if(a.smoothScroll){c.preventDefault();var d=b(this).attr("href"),d=d.substr(1,d.length),c=b(a.wrap).find("#"+d).position(),d=b(a.wrap).find("#"+d).children().first();d.length&&(c=d.position());b(a.wrap).parent().animate({scrollTop:c.top+"px"},a.scrollSpeed);return!1}};
a.timeoutPrint=function(c,d,f){if(c<f.attachments.length){var h=f.attachments[c];if(h.mime_type.indexOf("image")>-1)h=h.images.full,b("<img />",{src:h.url,height:h.height,width:h.width}).appendTo(d).lazyload({placeholder:a.placeholder,effect:"fadeIn",container:a.wrap.parent()});a.timeout=setTimeout(function(){a.timeoutPrint(c+1,d,f)},a.speed)}else clearTimeout(a.timeout),a.getting=!1};a.init();return a}})(jQuery);(function(b){function d(a){if(!a)return!1;var c=b("#header").find("a"),d=!1;b.each(c,function(){if(b(this).text().toLowerCase()==a)return d=b(this),!1});c=null;return d}function a(){var a=d("pictures");if(a)if(Ease.ie)a.attr({href:"http://subwaytiles.bennya.com",target:"_blank"});else{var c=b("#subwayTilesWrap");a.click(function(a){a.preventDefault();h||(h=new SyndicatedSubwayTiles({wrapId:"subwayTiles",smoothScroll:!0}));c.show(250)});b("#closeSubwayTiles").click(function(){c.hide(250)})}a=null}
function f(){if(b("#worksTop").length){var a=b("#worksTop").find("a"),c=b("#header").outerHeight()+b("#worksTop").outerHeight(),d=b("#works");d.css({marginTop:b("#worksTop").outerHeight()-18});var f=function(a){a.preventDefault();a=b(this).attr("href");a=a.substr(1,a.length);a=b("#works").find("#"+a).offset();b("html, body").animate({scrollTop:a.top-c+"px"},2*e)};b.each(a,function(){var a=b(this).attr("href");a&&a.indexOf("#")===0&&b(this).click(f)});a=null;d.find("img").click(function(){b(this).addClass("active").siblings().removeClass("active");
b(this).parent().parent().next().find("img").attr("src",b(this).attr("full"))});a=d.find(".pics").find("img");b.each(a,function(){var a=b(this).attr("full");(new Image).src=a});d=a=null}}function c(){b("#header nav").length&&(b("#header nav").each(function(){var a=b(this),c=b(this).find("li");b(window).resize(function(){var d=0;c.each(function(){d+=b(this).width()});var e=Math.floor((g/2-75-k-d)/(c.length-1)-3);a.is("#accessLeft")?c.not(":first").css({marginLeft:e}):c.not(":last").css({marginRight:e})});
c.each(function(){b(this).find("a").attr("href")===window.location.href&&b(this).addClass("current-menu-item current_page_item")})}),b(window).resize())}var e=350,g=900,k=35,h=!1;b(document).ready(function(){b("html.ie").length?Ease.ie=!0:Ease.ie=!1;b("html.lte8").length?Ease.lte8=!0:Ease.lte8=!1;typeof WebKitPoint!=="undefined"?Ease.webkit=!0:Ease.webkit=!1;c();f();b("#videos").length&&new EaseYouTubePlayer({user:"nakedincorners",playerIsPopup:!0,maxResults:6});b("#locations").length&&new EaseMap({zoom:2,
streetViewControl:!0,fitMarkers:!0,centerLat:36.153982,centerLng:-95.992775,dataCont:".locationList",dataBlock:".locationItem",dataAttr:"ease-data",locationKey:"ba_place_address",directionsLink:!1,blocksAreClickable:!0});if(b("#resumeHref").length){var e=b("#resumeHref").text();b("#header").find("a");var g=d("resume");g&&g.attr({href:e,target:"_blank"})}a()})})(jQuery);var _gaq=_gaq||[];_gaq.push(["_setAccount","UA-28492745-1"]);_gaq.push(["_trackPageview"]);
(function(){var b=document.createElement("script");b.type="text/javascript";b.async=!0;b.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";var d=document.getElementsByTagName("script")[0];d.parentNode.insertBefore(b,d)})();
